// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBwjOWCOeytvQG368AL5ALbQ7krUnfWKk',
    appId: '1:764217751836:web:8e7f1e92d1229c654062d9',
    messagingSenderId: '764217751836',
    projectId: 'jelantahku',
    authDomain: 'jelantahku.firebaseapp.com',
    storageBucket: 'jelantahku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCaljO8glmBIkKeA-LoD0zb6yvBHYrz0',
    appId: '1:764217751836:android:a1f8971a0e9627134062d9',
    messagingSenderId: '764217751836',
    projectId: 'jelantahku',
    storageBucket: 'jelantahku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopb3f9m7brMd6wJp4M6jSTlfghTxK3xs',
    appId: '1:764217751836:ios:cd8b1f0e8d9c2fc04062d9',
    messagingSenderId: '764217751836',
    projectId: 'jelantahku',
    storageBucket: 'jelantahku.firebasestorage.app',
    iosBundleId: 'com.jelantahku.jelantahKu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopb3f9m7brMd6wJp4M6jSTlfghTxK3xs',
    appId: '1:764217751836:ios:cd8b1f0e8d9c2fc04062d9',
    messagingSenderId: '764217751836',
    projectId: 'jelantahku',
    storageBucket: 'jelantahku.firebasestorage.app',
    iosBundleId: 'com.jelantahku.jelantahKu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBwjOWCOeytvQG368AL5ALbQ7krUnfWKk',
    appId: '1:764217751836:web:55260369e718079e4062d9',
    messagingSenderId: '764217751836',
    projectId: 'jelantahku',
    authDomain: 'jelantahku.firebaseapp.com',
    storageBucket: 'jelantahku.firebasestorage.app',
  );
}
